stages:
  - build
  - test
  - deploy

job 1:
  stage: build
  script: "echo `date`"

job 2:
  stage: test
  script: cat file1.txt file2.txt | grep -q "hello world"

job 3:
  stage: deploy
  script: cat file1.txt file2.txt | gzip > mypackagedzip.gz
  artifacts: 
    paths:
    - mypackagedzip.gz
